[workspace]
members = ["decal-core", "decal-macros", "decal-core/examples/gh_card", "decal-core/examples/gradients"]
default-members = ["decal-core"]
resolver = "2"

[workspace.package]
license = "MIT"
