[package]
name = "decal"
description = "Under development"
version = "0.0.0"
edition = "2021"
license.workspace = true
rust-version = "1.87.0"
repository = "https://github.com/mem-red/decal"

[dependencies]
cosmic-text = "0.14.2"
decal-macros = { path = "../decal-macros" }
taffy = "0.8.3"

[features]
helpers = []